#!/usr/bin/env python

import sys

from googlevoice import Voice
from googlevoice.util import input

voice = Voice()
voice.login()

outgoingNumber = sys.arg[0]
forwardingNumber = sys.arg[1] or None

voice.call(outgoingNumber, forwardingNumber)

if input('Calling now... cancel?[y/N] ').lower() == 'y':
    voice.cancel(outgoingNumber, forwardingNumber)