#!/usr/bin/env python

import sys

from googlevoice import Voice

voice = Voice()
voice.login("ryankshaw@gmail.com", "777lky")

outgoingNumber = sys.argv[0]
forwardingNumber = sys.argv[1] or None

voice.call(outgoingNumber, forwardingNumber)

if input('Calling now... cancel?[y/N] ').lower() == 'y':
    voice.cancel(outgoingNumber, forwardingNumber)